development:
  adapter: postgresql
  encoding: unicode
  database: guess_who_again_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: guess_who_again_test
  pool: 5
  username:
  password:
